### ISSUE TITLE
Upgrade to latest dox (vulnerability)

### ISSUE THREAD

**Issue by davedoesdev** [codeactual/apidox#13]
I did a `npm install apidox`. All installed fine. However, `dox` version 0.4.6 is getting installed as a dependency.
Now, apidox's `package.json` says:

```json
"dox": "^0.4.4"
```

which is fine but npmjs.com says the latest version of dox is 0.9.0.

Now, I had thought that the caret would allow anything below 1.0.0. However, then I read this on https://docs.npmjs.com/misc/semver:

> Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4
> Allows changes that do not modify the left-most non-zero digit in the [major, minor, patch] tuple. In other words, this allows patch and minor updates for versions 1.0.0 and above, patch updates for versions 0.X >=0.1.0, and no updates for versions 0.0.X.

which means we'll not get the latest dox.

The reason I want apidox to use the latest dox is I just got emails from github saying there's a vulnerability in a dependency (marked 0.3.6). This used to be used by dox but it now uses markdown-it.

**Comment by codeactual** [comment]
@davedoesdev Thanks. I've obviously not been able to maintain it properly. I've added push permission for you. Please let me know if I can help further.

**Comment by davedoesdev** [comment]
OK I've made the tests pass with the latest dox: https://github.com/davedoesdev/apidox/commit/acd40373005ef43c52d58742dbf012edd4f673cf

What do you think?

**Comment by codeactual** [comment]
Can you PR it? Travis CI will then get triggered. I just updated the config to use newer runtimes.

Basically I'm fine with it as long as the test-pass is reproducible.

**Comment by davedoesdev** [comment]
Fixed by https://github.com/codeactual/apidox/pull/15.

**Comment by davedoesdev** [comment]
@codeactual would you mind publishing to npm please?

**Comment by codeactual** [comment]
Done.

**Comment by davedoesdev** [comment]
Thanks. I'll now update https://github.com/davedoesdev/grunt-apidox to use 1.0.0 and re-generate the API docs for my projects which use it.
Hopefully the output should be identical!
